# Website settings
title: COPS IIT(BHU)
description: Official website of COPS, The Club of Programmers IIT(BHU) Varanasi.
keywords: iitbhu-cops,blog,cops,github,club,programmers,development,ml,cp,dev
baseurl:  '' # if you have suburl as homepage like '/homepage', please change it to '/homepage' and your repo's name should be 'homepage'
url: https://copsiitbhu.co.in  # url should be 'http://<github_username>.github.io/homepage' as before
# url: http://127.0.0.1:4000
img_path: /static/assets/img/blog  # url should be '/homepage/static/assets/img/blog' as before

# author -- index page "about me" section
author:  # change following line to your infomation.
  name: Club of Programmers  # Be used at blog posts' author.
  first_name: Club of Programmers  # Be used at index page about me section.
  last_name: IIT (BHU), Varanasi  # Be used at index page about me section.
  avatar: /static/assets/img/landing/avatar.jpg  # upload your avatar at directory and edit it.
  github_username: COPS-IITBHU  # Leave blank if you don't have now
  slack_username: cops-iitbhu
  googlegroup_username: copsiitbhu
  linkedin_id:  # Leave blank if you don't have now
  facebook_username: cops.iitbhu  # Leave blank if you don't have now
  twitter_username:   # Leave blank if you don't have now
  email: contact@copsiitbhu.co.in  # Leave blank if you don't have now
  cv:   # An online CV can be printed as PDF, leave blank if you don't have now
  # skill icons are on avatar's left and right side. Reference urls are http://fontawesome.io/ and http://fizzed.com/oss/font-mfizz
  skill_icon1:
    - name: fa-code
    - name: fa-linux
  skill_icon2:
    - name: fa-linux
    - name: fa-code
  desc: Official website of COPS, The Club of Programmers IIT(BHU) Varanasi.

# comment
disqus:  # if you wanna comment feature, go to https://disqus.com/ to get your configuration; if not, comment following two lines.
  name: iitbhu-cops

# analytics
## google analytics
ga:
  id: UA-128283984-1

## google optimize
go:
  # id:

## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## donation
donation: off  # type 'on'/'off' to choice display donation button at post page or not

## carousels
index_carousel: on  # index page carousel switch
blog_carousel: on  # blog page carousel switch

# scss
sass:
  style: compressed

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-redirect-from