- name: CSOC 2023
  resources:
    - title: Web Track
      tags:
        - cops
        - csoc
        - dev
        - frontend
      links:
        - label: Week 0
          url: https://cops-sdg.notion.site/cops-sdg/CSOC-23-Web-b73ab317d53744f8b00b21887c4ae1ab
    - title: App Dev Track
      tags:
        - cops
        - csoc
        - dev
        - app
      links:
        - label: Resources
          url: https://sagittariusa11.notion.site/CSOC-23-App-Dev-b874014ac84247bd932e815bc04cf65a
    - title: System Dev Track
      tags:
        - cops
        - csoc
        - dev
        - app
      links:
        - label: Resources
          url: https://harsh-raj.notion.site/CSOC-23-Systems-28a46b306e864f88a706eceff9c7248f
    - title: Game Dev track
      tags:
        - cops
        - csoc
        - dev
        - game
      links:
        - label: Resources
          url: https://github.com/Yash-Agarwal1708/csoc-23-GameDev-week-0
        - label: Resources
          url: https://github.com/Yash-Agarwal1708/csoc-23-GameDev-week-1
        - label: Resources
          url: https://github.com/Yash-Agarwal1708/csoc-23-GameDev-week-2
        - label: Resources
          url: https://github.com/Yash-Agarwal1708/csoc-23-GameDev-week-3
        - label: Resources
          url: https://github.com/Yash-Agarwal1708/csoc-23-GameDev-week-4
    - title: Web3 Dev Track
      tags:
        - cops
        - csoc
        - dev
        - web3
      links:
        - label: Resources
          url: https://vaibhav-1508.notion.site/CSOC-23-Web3-66e3550c6bed49fba5ef0f738348f3e4
- name: CSOC 2021
  resources:
    - title: Frontend Tasks
      tags:
        - cops
        - csoc
        - dev
        - frontend
      links:
        - label: Resources
          url: https://six-top-bb6.notion.site/CSOC-21-Dev-Frontend-014d55c642a74e6e885216e93c6e6f66
    - title: Backend Tasks
      tags:
        - cops
        - csoc
        - dev
        - backend
      links:
        - label: Resources
          url: https://persistent-tent-e83.notion.site/CSoC-21-Dev-Backend-640126aa2ec2473ab98f6fd316a229c9

- name: Workshops
  resources:
    - title: GSoC 101
      tags:
        - cops
        - gsoc
        - opensource
      links:
        - label: Slides
          url: https://docs.google.com/presentation/d/1pe1aiG_Cje2_zG8RshDnDqu3YNm3AVGvQfbt8s9Uq7o/edit
        - label: Session
          url: https://www.youtube.com/watch?v=kac2sPhohF8
    - title: OSS Hacktoberfest
      tags:
        - cops
        - opensource
        - hacktoberfest
        - git
      links:
        - label: Slides
          url: https://docs.google.com/presentation/d/1SzC5AjfVY0J-szO-K5WiWbGxeroAs_GDX7_pwQMazkQ/edit
        - label: Session
          url: https://www.youtube.com/watch?v=AkitdjVYspo
    - title: Basics of web development
      tags:
        - cops
        - webdev
        - html
        - css
        - js
      links:
        - label: Slides
          url: https://docs.google.com/presentation/d/1fXokS_Dm7wkVIV9y911vP2as1AcX7MNH4FyONbz3mAg/edit
        - label: Session
          url: https://www.youtube.com/watch?v=4EvnVRVZ4os

- name: CSOC 2020
  resources:
    - title: DEV track
      tags:
        - cops
        - csoc
        - web
        - django
        - flutter
        - rest
        - api
        - ar/vr
      links:
        - label: Resources
          url: https://cops-iitbhu.github.io/csoc-2020-dev-resources/
        - label: Leaderboard
          url: https://csoc.copsiitbhu.co.in/

- name: COPS Workshop Series
  resources:
    - title: PROG 101
      tags:
        - cops
        - coding
      links:
        - label: Slide
          url: https://drive.google.com/file/d/19ea-8kma3XjM3YmkE4gDTon9P9JZp5Ug/view
    - title: Linux Installation Fest
      tags:
        - linux
      links:
        - label: Slide
          url: https://docs.google.com/presentation/d/1wML0NohWlSMDCWt2pUx0XChzXo_PtCpod5lFXp4YyuU/edit?usp=sharing
    - title: Web Dev
      tags:
        - web
        - api
        - html
        - css
        - js
      links:
        - label: Slide
          url: https://docs.google.com/presentation/d/1kMj_iaQVrtE7Df9xIcp2_K--cqlnbWFNP6o_LBFoNuw/edit?usp=sharing

- name: Open Source
  resources:
    - title: Dev 055
      tags:
        - oss
        - git
        - hacktoberfest
      links:
        - label: Slide
          url: https://drive.google.com/open?id=1P0JXEo_LkuhqtZ84LTA2x2xU56jttyCL
    - title: GSoC 101
      tags:
        - gsoc
        - oss
      links:
        - label: Slide
          url: https://drive.google.com/open?id=1C5vi9NtL-o46UiYrIfM6iZhGRYEFzkf7-JhsaqQvyCE
    - title: Hello GSoC & Outreachy!
      tags:
        - gsoc
        - outreachy
      links:
        - label: Slide
          url: https://drive.google.com/open?id=1zolLBrwAF4fecfy1aFMK46OpPFbl9g5YPsMJ1Y9nvPM

- name: Dev Extravaganza
  link:
    label: Details
    url: /events/extravaganza/
  resources:
    - title: Unity3D Game Dev
      tags:
        - game
        - unity
      links:
        - label: Slide
          url: https://drive.google.com/open?id=1oIwKxAuAGvRvu08JT5bfAH-tVQaTQsbYy9fxYTBvbb8
    - title: Deployment with AWS
      tags:
        - deploy
        - cloud
        - aws
      links:
        - label: Slide
          url: https://drive.google.com/open?id=1ifZafQNhoa2YNi6dsr07wAvbGDRCQNvP
    - title: Twilio WhatsApp API
      tags:
        - api
        - twilio
      links:
        - label: Slide
          url: https://drive.google.com/open?id=1vZ5yHQA3aPpp6K5qWD-vvQ3qZXqiWtbaFXjt8v6TRO8

- name: Dev Talks
  link:
    label: Github Repo
    url: https://github.com/COPS-IITBHU/DevTalks
  resources:
    - title: 3719 - Building MMORPG
      tags:
        - game
        - websockets
        - multiplayer
      links:
        - label: Slide
          url: https://drive.google.com/open?id=1C1RU8RKeYmdotay6Wru-ohmunO11znRorcDkSAjGY4w

        - label: Github
          url: https://github.com/shivanshs9/MMORPG-TLO

- name: CSOC Dev weeks
  link:
    label: Details
    url: /events/csoc/
  resources:
    - title: Week 1
      tags:
        - git
        - github
      links:
        - label: FB Post
          url: https://www.facebook.com/cops.iitbhu/posts/1052913788247860
    - title: Week 2
      tags:
        - html
        - js
        - frontend
      links:
        - label: Blog
          url: /blog/2019/05/31/CSOC-Dev-Week-2.html
    - title: Week 3
      tags:
        - python
        - django
        - backend
        - api
      links:
        - label: Blog
          url: /blog/2019/06/08/CSOC-Dev-Week-3.html
  tasks:
    - title: Week 2
      tags:
        - html
        - frontend
      links:
        - label: Github
          url: https://github.com/COPS-IITBHU/CSOC-dev-week2
    - title: Week 3
      tags:
        - django
        - backend
      links:
        - label: Github
          url: https://github.com/COPS-IITBHU/csoc-dev-week3
    - title: Week 4
      tags:
        - oss
      links:
        - label: Github
          url: https://github.com/COPS-IITBHU/csoc-dev-week4

- name: Dev Winter Camp
  link:
    label: Site
    url: http://wintercamp.copsiitbhu.co.in/
  resources:
    - title: JS course
      tags:
        - js
        - frontend
      links:
        - label: Udacity
          url: https://www.udacity.com/course/intro-to-javascript--ud803
    - title: Github Pages
      tags:
        - deploy
        - frontend
        - github
      links:
        - label: YouTube
          url: https://www.youtube.com/watch?v=2MsN8gpT6jY
  tasks:
    - title: Tic Tac Toe (2019)
      tags:
        - html
        - frontend
        - js
        - game
      links:
        - label: Github
          url: https://github.com/COPS-IITBHU/winter19-task1
